version: '3.8'

services:
  go-pharmacy-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-pharmacy-service
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./docs:/app/docs
    environment:
      AUTH_TOKEN: hippotoken
      DATABASE_PATH: /app/data/pharmacy.db
      PHARMACIES_CSV_PATH: /app/data/pharmacies/pharmacies.csv
      CLAIMS_DATA_PATH: /app/data/claims
      REVERTS_DATA_PATH: /app/data/reverts
      PORT: 8080
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - go-pharmacy-service

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-data: